name: Frontend - CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  LINT:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm install

      - name: Lint
        run: |
          cd starter/frontend
          npm run lint

  TEST:
    runs-on: ubuntu-latest
    needs: LINT
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm install

      - name: Tests
        run: |
          cd starter/frontend
          npm test

  BUILD:
    runs-on: ubuntu-latest
    needs: [LINT, TEST]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./starter/frontend
          push: true
          tags: |
            521474520625.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
            521474520625.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}

  DEPLOY:
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubectl with AWS EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name cluster

      - name: Deploy to Kubernetes
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=521474520625.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}
          kustomize build | kubectl apply -f -
